### ISSUE TITLE
[TODO] Deprecate Sandhook

### ISSUE THREAD

**Issue by yujincheng08** [LSPosed/LSPosed#179]
YAHFA and SandHook are now very similar but SandHook is much heavier than YAHFA. So we are going to deprecate it in future versions by the following steps for each version:

- [x] deprecate in manager and installation, showing hints that it would be deprecated
- [x] deprecate variant switch in manager and installation, and can only switch by modifying `/data/adb/lspd/config/variant` manually
- [x] completely remove SandHook from the backend but keep the multi-variant support codes (those interfaces)
- [x] remove multi-variant support codes

Any comment on this topic is welcomed.

**Comment by kotori2** [comment]
> remove multi-variant support codes

I think it's unnecessary

**Comment by yujincheng08** [comment]
> > remove multi-variant support codes
> 
> I think it's unnecessary

Those `YahfaImpl` and `getImplConfig` are ugly though

**Comment by Pandemic-XDA** [comment]
Keep the sandhook please :)

**Comment by tehcneko** [comment]
@Pandemic-XDA no
