### ISSUE TITLE
[TODO] Separate `core` into multiple modules

### ISSUE THREAD

**Issue by yujincheng08** [LSPosed/LSPosed#875]
Currently, the `core` contains multiple functions and is very messy. It's better to separate the `core` into multiple modules:
- [x] `hooker`: YAHFA, some Xposed APIs and corresponding native hooks. Export some interfaces to load and initialize it.
- [x] `lspd`: the backend to load configuration and deliver modules.
- [x] `bridge`: the bridge between lspd and frontend in the system server via the binder.
- [x] `loader`: a frontend (using riru/zygisk) to load and initialize hooker and load configuration via binder from the bridge.

For the loader, there should be a `base_loader`, and the `riru_loader` inherits it. If Magisk hook is done, we can have another `magisk_loader`. For LSPatch, it can have a `patch_loader`.

With such a layout, LSPatch could be better implemented: it just needs to replace `riru` with another loader, replace lspd into an app. Further, hooker can be a library that could be integrated by other apps.

**Comment by aaeuft** [comment]
غالي

**Comment by Dr-TSNG** [comment]
#1756 #1766
